[project]
name = "secondapp"
version = "0.1.0"
description = "A second LLM App"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "langchain-groq==0.2.1",
    "langchain==0.3.7",
    "streamlit>=1.40.1",
]
