name: mikegpt-docker-build

on:
  push:
    branches:
      - "main"
    paths:
    - Dockerfile
    - main.py
    - .github/workflows/docker-build.yaml

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
    
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push Docker
        run: | 
          docker build -t mdh266/mikegpt:cloudrun .
          docker push mdh266/mikegpt:cloudrun 
  
      - name: Google Cloud Auth
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
          
      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy mikegpt \
          --image=mdh266/mikegpt:cloudrun \
          --set-env-vars=GROQ_API_KEY=${{ secrets.GROQ_API_KEY }} \
          --region=us-central1 \
          --project=${{ secrets.GOOGLE_PROJECT_ID }} #\
          # && gcloud run services update-traffic mikegpt --region=us-central1 --to-latest 
